### ISSUE TITLE
Are you considering first-time speakers ?

### ISSUE THREAD

**Issue by claudiahdz** [fromthefront/ama#2]

**Comment by cedmax** [comment]
Absolutely! We actually had a few first-time speakers on our stage over the last few years and we are really proud of it. 

I won't lie and tell you it's easy to be on that stage (so maybe some meet-up experience or anything like that would help you feeling more comfortable) but we won't discard a good talk because of inexperience. On the top of that some slots are reserved for an anonymous selection based on the content, hence we wouldn't know anyway.
