### ISSUE TITLE
CFP: What is a talk topic that's not been covered in previous years but you really want to hear about?

### ISSUE THREAD

**Issue by jegtnes** [fromthefront/ama#5]
Alternatively, something that's already been covered but you want to hear more about, or want a different angle on.

**Comment by cedmax** [comment]
Wow this is a tough one!

And quite personal as well since the selection is a process that involves the whole team.
I'd rather have anyone of us step in the conversation rather than giving you a "recipe" (which I couldn't probably do anyway). @mattcav @brassy- @jsDotCr @fabiovenni 

As for me I don't have a straight answer: the line up of FTF is built up by urgency and opportunity. 
The urgency is usually defined by the call for papers itself (and for us it has hardly a technical or topic related scope, this year it's about "change[1]")

The opportunity gets clear as soon as we access the submissions: we can see what content is proposed and what could match with the content of the invited speakers to have a conference that "makes sense"™.

That's my bit, let's see what the others have to say about it :)
 <br/> <br/> <br/>

[1] from the CFP: 

> Change is such a vital part of the world around us, that often we don’t notice it happening; seasons, hair-styles... js libraries.
> 
> It can be disruptive and revolutionary, or quiet and subtle, touching all aspects of our personal and professional lives - be it fixing a misaligned element, writing about our experiences, or welcoming a new friend in our lives.
> 
> We want to celebrate change, and want you to share your stories of it with From the Front’s attendees. How have you embraced it, used it to face new opportunities, how has it impacted you.
> 
> Change is the only constant.

**Comment by mattcav** [comment]
I have to say that it's pretty hard to pick something that I would prefer. There are many good topics, and a lot of different experiences I would love to hear at FTF. But If I have to take only one, I would start from something that try to changes a (common) point of view about something. 

Our industry isn't that old, there's no so much history and traditions. However, there are a lot of things that we often take for granted, only because "we used to do like this". Many people just don't stop and think about "why" we're doing something, and if this could be improved. 

Technologies, but also the process and the business, are moving fast. We should be able, more than ever, to feel the flow of those changes and constantly rethink about how we solve problems.

Jeremy Keith's talk (http://2014.fromthefront.it/speakers.html#jeremy-keith) and the Jon Gold's one (https://vimeo.com/116870994) are actually good examples for the stuff I like. Strong, mind-blowing opinions that push people outside their "traditional" approach.

**Comment by jsDotCr** [comment]
When the CFP closes, our mailbox explodes: that's because all of us get together discussing about _all_ the proposals we've received. And this usually produces looong threads because we try to push towards some topics rather than others, based on our backgrounds and the different level of awareness over some subjects. At the end of the day, we end up having a balanced conference ranging from deeply technical topics to anything that surrounds us as frontenders.

When it comes to me, I prefer something that arouses curiosity, by allowing me to have a broader and more positive view on _what_ I do, on _what_ surrounds me, and on **who** surrounds me. I'm an open-minded information sponge when I'm at conferences: I need inputs, especially if it's something I can't find on the web by myself, such as motivations behind a technical choice, a workflow, soft skills.
The more the better.
It's then up to me decide what I need to work on, either personally or team-wise.

A talk should raise issues, questions to myself, it might end up triggering some change, getting out of my own comfort zone: am I doing this right? Is this a better approach to tackle the issue I'm currently working on? What if my PM is right and I am wrong?
You should instil doubts so you let people actually think about your thesis and eventually discuss, embrace, evolve them.

#abbidubbi

**Comment by jegtnes** [comment]
These are brilliant, thoughtful, and splendid replies, folks. :+1: Thank you very much for your time. I'll mull this over and see if I can conjure something good.
